{{- if and .Values.prometheus.jmx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cp-zookeeper.fullname" . }}-jmx-configmap
  labels:
    app: {{ template "cp-zookeeper.name" . }}
    chart: {{ template "cp-zookeeper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  jmx-zookeeper-prometheus.yml: |+
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:{{ .Values.jmx.port }}/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    {{- if .Values.prometheus.jmx.whitelistObjectNames }}
    whitelistObjectNames:
{{ toYaml .Values.prometheus.jmx.whitelistObjectNames | trim | indent 4 }}
    {{- end }}
    rules:
{{ tpl .Values.prometheus.jmx.rules . | indent 4 }}
{{- end }}
